### ISSUE TITLE
can not caculate the 1001111001100000100100000000011110100000000000001000001000110000

### ISSUE THREAD

**Issue by buuug7** [greycubesgav/sqlite-phhammdist#1]
```
SELECT phhammdist(1101001011001010011001100001001000011100010000100100000010000100, 1000010101011101010101001110100011000000000000000111100001110000);
```
SQL error or missing database (phhammdist: both arguments need to be of type TEXT or both arguments need to be of type INTEGER.)

IF

```
SELECT phhammdist('1101001011001010011001100001001000011100010000100100000010000100', '1000010101011101010101001110100011000000000000000111100001110000');
```

always return 0

**Comment by greycubesgav** [comment]
Unfortunately sqlite has very limited data types of its own (https://www.sqlite.org/datatype3.html), and does not have a binary data type, so you will need to convert your binary number a hexadecimal string.

For example, using python on the command line to convert your binary number to a hexadecimal string:

```
python -c 'print "{0:0>4X}".format(int("1101001011001010011001100001001000011100010000100100000010000100", 2))'
D2CA66121C424084
```

```
python -c 'print "{0:0>4X}".format(int("1000010101011101010101001110100011000000000000000111100001110000", 2))'
855D54E8C0007870
```

Run the phhammdist function with the two output strings from above:

```
select phhammdist('D2CA66121C424084','855D54E8C0007870');
> 7
```

You'll need to look into the easiest way for you to do your conversion in whatever language you are using to wrap around sqlite.

**Comment by buuug7** [comment]
@greycubesgav  thanks your reply,  i already switch database to mysql for calculate Hamming distance.  but i think use the hamming in sqlite is quite a challenge with less extension knowlege.
